name: Deploy pages

on: push

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run: npm i -g @slidev/cli
      - name: Install theme-default
        run: npm i -g @slidev/theme-default
      - name: Install for PDF
        run: npm i -g playwright-chromium
      - name: Build
        run: slidev build --base /slides-gh-actions-n-runners/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    if: github.ref_name == 'main'
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
